# Ignore everything that is not white listed below
*

!/.codeclimate.yml
!/.eslintignore
!/.eslintrc
!/.jsdoc
!/.mdlrc
!/.npmrc
!/.nvmrc
!/.scannerwork
!/CODE_OF_CONDUCT.md
!/CONTRIBUTING.md
!/Dockerfile
!/Dockerfile.dockerignore
!/LICENSE
!/README.md
!/bin
!/docs
!/images
!/mbTest
!/package-lock.json
!/package.json
!/releases.json
!/scripts
!/src
!/tasks
!/test

